# Generated by Django 3.2 on 2021-05-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tweet_id', models.BigIntegerField()),
                ('body', models.TextField(max_length=280)),
                ('author_handle', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
