# Generated by Django 3.2 on 2021-05-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='author_handle',
            new_name='author_screen_name',
        ),
    ]
